trigger:
  batch: true
  branches:
    include:
    - master

variables:
- group: secret

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'Build Vue'

- script: |
    npm install -g firebase-tools
    firebase deploy --token $(token)
  displayName: 'Firebase Deploy'